Fix types
```
$ npx tsc --noEmit && npx next build && npx next dev --port 4440
.next/types/app/agents/[agentName]/layout.ts:34:31 - error TS2344: Type 'Readonly<{ children: ReactNode; params: { agentName: string; }; }>' does not satisfy the constraint 'LayoutProps'.
  Types of property 'params' are incompatible.
    Type '{ agentName: string; }' is missing the following properties from type 'Promise<any>': then, catch, finally, [Symbol.toStringTag]

34 checkFields<Diff<LayoutProps, FirstArg<TEntry['default']>, 'default'>>()
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~

Found 1 error in .next/types/app/agents/[agentName]/layout.ts:34
```