Fixing types - Expose `capabilities`
```log
../../src/llm-providers/agent/Agent.ts:42:14 - error TS2420: Class 'Agent' incorrectly implements interface 'AgentBasicInformation'.
  Property 'capabilities' is missing in type 'Agent' but required in type 'AgentBasicInformation'.
                                                                    Agent' incorrectly implements interface 'AgentBasicInformation'.
42 export class Agent extends AgentLlmExecutionTools implements LlmE type 'AgentBasicInformation'.xecutionTools, AgentBasicInformation {
                ~~~~~                                               xecutionTools, AgentBasicInformation {

  ../../src/book-2.0/agent-source/AgentBasicInformation.ts:123:5
    123     capabilities: AgentCapability[];
            ~~~~~~~~~~~~
    'capabilities' is declared here.
```