[✨🔄] Fix refusing to allow a Personal Access Token to create or update workflow `.github/workflows/publish-book-editor-macos.yml` without `workflow` scope
```
Copying ./books to ./packages/cli/books
Copying ./servers.ts to ./packages/cli/servers.ts
Copying ./security.config.ts to ./packages/cli/security.config.ts
Agents-server app copied successfully
Copying ./agents/default/developer.book to ./packages/cli/agents/default/developer.book
8️⃣  Test that nothing what should not be published is published
Skipping the bundler, skipping the tests for bundle content
9️⃣  Make publishing instructions for Github Actions
--- Commit ---
📦 Generating packages `0.112.0-123`
⏩ Not commiting because nothings changed

> postversion
> git push && git push --tags && npm run update-version-in-config-commit && npm run generate-packages-commit && npm run use-packages

Enumerating objects: 1126, done.
Counting objects: 100% (887/887), done.
Delta compression using up to 6 threads
Compressing objects: 100% (192/192), done.
Writing objects: 100% (193/193), 332.81 KiB | 1.61 MiB/s, done.
Total 193 (delta 163), reused 0 (delta 0), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (163/163), completed with 96 local objects.
remote: error: GH013: Repository rule violations found for refs/heads/main.
remote: Review all repository rules at https://github.com/webgptorg/promptbook/rules?ref=refs%2Fheads%2Fmain
remote:
remote: - refusing to allow a Personal Access Token to create or update workflow `.github/workflows/publish-book-editor-macos.yml` without `workflow` scope
remote:
To https://github.com/webgptorg/promptbook.git
 ! [remote rejected]     main -> main (push declined due to repository rule violations)
error: failed to push some refs to 'https://github.com/webgptorg/promptbook.git'
npm error code 1
npm error path C:\Users\me\work\ai\promptbook
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c git push && git push --tags && npm run update-version-in-config-commit && npm run generate-packages-commit && npm run use-packages
npm error A complete log of this run can be found in: C:\Users\me\AppData\Local\npm-cache\_logs\2026-06-21T18_57_16_298Z-debug-0.log

me@DESKTOP-2QD9KQQ MINGW64 ~/work/ai/promptbook (main)
$

```